core/blog/urls.py
from django.urls import path

from .views import CategoryDetail,NewsView, newsdetail, search_result

app_name = 'blog'
urlpatterns = [
    path('', NewsView.as_view(), name='news'),
    path('category/<int:pk>', CategoryDetail.as_view(), name='category_detail'),
    path('news/<int:pk>/', newsdetail, name='news_detail'),
    path('search-result/', search_result, name='search-result'),

]



# path('post/<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
# path('post/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
# path('post/create/', PostCreate.as_view(), name='post_create'),

core/core/urls.py
from django.contrib import admin
from django.template.context_processors import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('user/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/urls.py
from django.urls import path, re_path

from .views import LoginView, SignUpConfirmView, SignupDoneView, SignupView, home, logout, \
    PasswordReset, PasswordResetDone, PasswordResetComplete, PasswordResetConfirm

app_name = 'user'
urlpatterns = [
    path('', home, name='home'),
    path('signin/', LoginView.as_view(), name='signin'),
    path('logout/', logout, name='logout'),

    path('signup/', SignupView.as_view(), name='signup'),
    path('signup/done/', SignupDoneView.as_view(), name='signup-done'),
    re_path(
        r'^signup/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        SignUpConfirmView.as_view(),
        name='signup-confirm',
    ),

    path('password-reset/', PasswordReset.as_view(), name='password-reset'),
    path('password-reset/done', PasswordResetDone.as_view(), name='password-reset-done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password-reset-confirm'),
    path('password-reset/complete', PasswordResetComplete.as_view(), name='password-reset-complete')
]

core/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    pass

core/user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UsernameField, AuthenticationForm
from django.forms import widgets


class UserCreationForm(forms.ModelForm):
    username = UsernameField(
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control',
                                      'placeholder': 'Имя пользователя'}),
    )
    email = forms.EmailField(
        required=True,
        widget=widgets.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Адрес электронноый почты'
        }),
    )

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password',)
        widgets = {
            'password': widgets.PasswordInput(attrs={'class': 'form-control',
                                                     'placeholder': 'Пароль'}),
        }

    def clean_email(self):
        email = self.cleaned_data["email"]
        users_found = get_user_model().objects.filter(email__iexact=email).exists()

        if users_found:
            raise forms.ValidationError("Пользователь с таким именем уже существует")

        return email

    def save(self):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        user.email = self.cleaned_data["email"]
        user.is_active = False
        user.save()
        return user

class UserLoginForm(AuthenticationForm):
    username = UsernameField(label=("Имя пользователя"),
                             widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control',
                                                           'placeholder': 'Имя пользователя'}))
    password = forms.CharField(
        label=("Пароль"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autofocus': True, 'class': 'form-control',
                                          'placeholder': 'Пароль'}),
    )

core/user/views.py
from django.conf import settings
from django.contrib.auth import get_user_model, login, views as auth_views
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.http import base36_to_int, int_to_base36
from django.utils.translation import ugettext_lazy as _
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView

from .forms import UserCreationForm, UserLoginForm


def home(request):
    return render(request, 'profile/home.html')


def logout(request):
    request.session.flush()
    return redirect('/user/')


class LoginView(auth_views.LoginView):
    form_class = UserLoginForm
    template_name = 'user/login.html'

# class LogoutView(auth_views.LogoutView):
#     template_name = 'user/logout.html'


class SignupView(CreateView):
    template_name = 'user/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('user:signup-done')

    def form_valid(self, form):
        ret = super().form_valid(form)
        site_name = 'Local Forum'
        domain = 'localhost'
        uid = int_to_base36(self.object.id)
        token = default_token_generator.make_token(self.object)
        mail_context = {
            'email': self.object.email,
            'domain': domain,
            'site_name': site_name,
            'uid': uid,
            'user': self.object,
            'token': token,
            'url': self.request.build_absolute_uri(reverse(
                'user:signup-confirm',
                kwargs={'uidb36': uid, 'token': token}
            ))
        }

        send_mail(
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[self.object.email],
            message='',
            subject=_('Спасибо, ваша регистрация прошла успешно!'),
            html_message=render_to_string(template_name='user/email/signup.html', context=mail_context),
        )
        return ret


class SignupDoneView(TemplateView):
    template_name = 'user/signup-done.html'


class SignUpConfirmView(View):
    def get(self, request, *args, **kwargs):
        uidb36 = kwargs.get('uidb36')
        token = kwargs.get('token')
        try:
            uid_int = base36_to_int(uidb36)
        except ValueError:
            raise Http404

        user = get_object_or_404(get_user_model(), id=uid_int)

        if default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()

        login(request, user=user)
        return redirect('cwt:home')


class PasswordReset(auth_views.PasswordResetView):
    template_name = 'user/password/reset.html'
    email_template_name = 'user/password/reset-email.html'
    success_url = reverse_lazy('user:password-reset-done')


class PasswordResetDone(auth_views.PasswordResetDoneView):
    template_name = 'user/password/done.html'

class PasswordResetConfirm(auth_views.PasswordResetConfirmView):
    template_name = 'user/password/reset-confirm.html'
    success_url = reverse_lazy('user:password-reset-complete')

class PasswordResetComplete(auth_views.PasswordResetCompleteView):
    template_name = 'user/password/reset-complete.html'

core/user/templates/user/password/done.html
{% extends 'base.html' %}
{% block nav %}
{% endblock %}
{% block filter %}
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6 ml-auto mr-auto">
        <div class="card">
            <div class="card-header">Восстановление доступа к странице</div>
            <div class="card-body">
                <p>Мы отправили вам инструкции по восстановлению доступа по электронной почте,
                    если на указанный вами адрес электронной почты существует учетная запись.
                    Вы должны получить письмо в ближайшее время.</p>
                <p>Если вы не получили письмо, убедитесь,
                    что вы ввели адрес, который вы зарегистрировали, и проверьте папку со спамом.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/user/templates/user/password/reset-complete.html
{% extends 'base.html' %}
{% block nav %}
{% endblock %}
{% block filter %}
{% endblock %}
{% block title %}Password reset{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-6 ml-auto mr-auto">
            <div class="card">
                <div class="card-header">Восстановления доступа</div>
                <div class="card-body">
                    <p>Ваш пароль успешно изменен. Вы можете войти перейдя по сылке снизу.</p>
                    <p><a href="{% url 'user:signin' %}">Войти</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/user/templates/user/password/reset-confirm.html
{% extends 'base.html' %}
{% block nav %}
{% endblock %}
{% block filter %}
{% endblock %}
{% block title %}Password reset{% endblock %}

{% block content %}
<div class="row">
    <div class="col-6 ml-auto mr-auto">
        <div class="card">
            <div class="card-header">Восстановление доступа</div>
            <div class="card-body">
                {% if validlink %}
                    <p>Пожалуйста, введите новый пароль дважды, чтобы мы могли убедиться в правильности написания</p>
                    <form method="post">{% csrf_token %}
                        <fieldset class="module aligned">
                            <form action="" method="post" class="form">
                                {% if form.non_field_errors %}
                                    <div class="non-field-errors alert alert-danger">
                                        {% for err in form.non_field_errors %}
                                            <p class="form-error">{{ err }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}

                                {% for field in form %}
                                    <fieldset class="form-group row mb25 {% if field.errors %}has-error{% endif %}">
                                        <div class="col-md-12">
                                            <label>
                                                {{ field.label }}
                                            </label>
                                            {% if field.errors %}
                                                {{ field }}
                                            {% else %}
                                                {{ field }}
                                            {% endif %}
                                            {% for err in field.errors %}
                                                <div class="form-control-feedback invalid-feedback">{{ err }}</div>
                                            {% endfor %}
                                            <small class="form-text text-muted">
                                                {{ field.help_text }}
                                            </small>
                                        </div>
                                    </fieldset>
                                {% endfor %}

                                <div class="form-actions text-center">
                                    {% csrf_token %}
                                    <button type="submit" role="button" class="btn btn-primary">Поменять пароль</button>
                                </div>
                            </form>
                        </fieldset>
                    </form>
                {% else %}
                    <p>Введенные пароли не совпадают, пожалуйста введите заново</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/user/templates/user/password/reset-email.html
    You're receiving this email because you requested a password reset for your user account at
        {{ site_name }}.

    "Please go to the following page and choose a new password:"
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'user:password-reset-confirm' uidb64=uid token=token %}
    {% endblock %}
    "Your username, in case you've forgotten:"  {{ user.get_username }}

 "Thanks for using our site!"
    The {{ site_name }} team

core/user/templates/user/password/reset.html
{% extends 'base.html' %}
{% block nav %}
{% endblock %}
{% block filter %}
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6 ml-auto mr-auto mt-5">
        <div class="card">
            <div class="card-header bg-primary text-white">Восстановление доступа</div>
            <div class="card-body">
                <form method="post">{% csrf_token %}
                    <fieldset class="module aligned">
                        <form action="" method="post" class="form">
                            {% if form.non_field_errors %}
                                <div class="non-field-errors alert alert-danger">
                                    {% for err in form.non_field_errors %}
                                        <p class="form-error">{{ err }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}

                            {% for field in form %}
                                <fieldset class="form-group row mb25">
                                    <div class="col-md-12">
                                        <label>
                                            {{ field.label }}
                                        </label>
                                        {% if field.errors %}
                                            {{ field }}
                                        {% else %}
                                            {{ field }}
                                        {% endif %}
                                        {% for err in field.errors %}
                                            <div class="form-control-feedback invalid-feedback">{{ err }}</div>
                                        {% endfor %}
                                        <small class="form-text text-muted">
                                            {{ field.help_text }}
                                        </small>
                                    </div>
                                </fieldset>
                            {% endfor %}

                            <div class="form-actions text-center">
                                {% csrf_token %}
                                <button type="submit" role="button" class="btn btn-primary ">Восстановление доступа</button>
                            </div>
                        </form>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}