core/blog/urls.py
from django.urls import path

from .views import CategoryDetail,NewsView, newsdetail, search_result

app_name = 'blog'
urlpatterns = [
    path('', NewsView.as_view(), name='news'),
    path('category/<int:pk>', CategoryDetail.as_view(), name='category_detail'),
    path('news/<int:pk>/', newsdetail, name='news_detail'),
    path('search-result/', search_result, name='search-result'),

]



# path('post/<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
# path('post/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
# path('post/create/', PostCreate.as_view(), name='post_create'),

core/core/urls.py
from django.contrib import admin
from django.template.context_processors import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('user/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/urls.py
from django.urls import path, re_path

from .views import LoginView, SignUpConfirmView, SignupDoneView, SignupView, home, logout, \
    PasswordReset, PasswordResetDone, PasswordResetComplete, PasswordResetConfirm

app_name = 'user'
urlpatterns = [
    path('', home, name='home'),
    path('signin/', LoginView.as_view(), name='signin'),
    path('logout/', logout, name='logout'),

    path('signup/', SignupView.as_view(), name='signup'),
    path('signup/done/', SignupDoneView.as_view(), name='signup-done'),
    re_path(
        r'^signup/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        SignUpConfirmView.as_view(),
        name='signup-confirm',
    ),

    path('password-reset/', PasswordReset.as_view(), name='password-reset'),
    path('password-reset/done', PasswordResetDone.as_view(), name='password-reset-done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password-reset-confirm'),
    path('password-reset/complete', PasswordResetComplete.as_view(), name='password-reset-complete')
]

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
   {% block title %} <title>News</title>{% endblock %}
    <link rel="stylesheet" href="{% static 'custom/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
    <img src="https://2.bp.blogspot.com/-vaE0ccmRU-M/XMdihsy3E8I/AAAAAAAAACo/8Ryejr7_QBwSRiEHWBcv_A8PDkGs5dDbgCLcBGAs/s1600/logo1.png"
         width="30" height="30" class="">
    <a class="navbar-brand" href="{% url 'blog:news' %}">News</a>
      <ul class="navbar-nav ml-auto">
        {% if not request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link btn-sm" href="{% url 'user:signin' %}"> Войти </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link btn-sm" href="{% url 'user:signup' %}"> Регистрация </a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link btn-sm" href="{% url 'user:logout' %}">Выйти</a>
        </li>
        {% endif %}
      </ul>
</nav>
{% endblock %}
{% block filter %}
<div class="container mt-5 ml-2">
  <div class="row">
    <div class="col-3 border-primary ">
        <ul class="nav flex-column border border-primary sticky-top" id="menu">
            <li class="nav-link bg-primary text-white">Категории</li>
            <li><a class="nav-link" id="active" href="{% url 'blog:news' %}"> Все </a></li>
            {% for category in categories %}
                <li><a class="nav-link text-dark" href="{{ category.get_absolute_url }}">{{ category.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-9">
      <form class="" action="{% url 'blog:search-result' %}">
        <div class="input-group mb-3">
          <input class="form-control border-primary" placeholder="Поиск по сайту" name="search">
          <div class="input-group-append">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Найти</button>
          </div>
        </div>
      </form>
{% endblock %}
      {% block content %}
      {% endblock %}
    </div>
  </div>
</div>
</body>
</html>